from django.urls import path

from plus.views import (
    index, products,
    articles_list_view, article_detail_view,
    register_view, quick_register_view, registration_success_view,
    check_username_availability, check_email_availability, suggest_usernames,
    profile_completion_view,
    custom_login_view, custom_logout_view, ajax_login, send_password_reset_email,
    user_profile_view, check_login_status, validate_login_credentials, change_password, set_password,
    send_phone_verification_code, phone_login, phone_profile_update_view, verify_email_change,
    verify_phone_in_profile,
    google_login, google_callback, facebook_login, line_login,
    verify_email, resend_verification_email, password_reset_confirm,
    product_detail_view, search_products, get_categories_api, submit_review, quick_view_product, delete_review,
    cart_view, cart_count_api, add_to_cart, update_cart_item, remove_cart_item, cart_totals, checkout, calculate_checkout_price,
    payment_view, process_payment, payment_success_view, payment_failed_view,
    linepay_confirm, linepay_cancel,
    order_list_view, order_detail_view, cancel_order_view, confirm_receipt_view,
    wishlist_view, toggle_wishlist,
    notification_list_view, notification_detail_view, notification_toggle_read,
    notification_delete, notification_api, notification_unread_count_api, notification_mark_all_read,
    notification_batch_action,
    newsletter_subscribe,
    privacy_policy_view, terms_of_service_view, delete_account_view,
    shipping_info_view, return_policy_view, faq_view, contact_us_view,
    goal_management_view, update_goal_view, add_weight_log_view, weight_log_api,
    food_search_api, add_nutrition_log_view, update_nutrition_log_view, delete_nutrition_log_view,
    nutrition_log_api,
)

urlpatterns = [
    path('account/password-reset/', send_password_reset_email, name='password_reset'),
    path('account/password-reset/confirm/<str:token>/', password_reset_confirm, name='password_reset_confirm'),
    path('account/verify-email/<str:token>/', verify_email, name='verify_email'),
    path('account/resend-verification-email/', resend_verification_email, name='resend_verification_email'),
    path('account/verify-email-change/<str:token>/', verify_email_change, name='verify_email_change'),

    path('', index, name='home'),
    path('products/', products, name='products'),
    path('search/', search_products, name='search'),

    path('login/', custom_login_view, name='login'),
    path('logout/', custom_logout_view, name='logout'),
    path('auth/google/login/', google_login, name='google_login'),
    path('auth/google/callback/', google_callback, name='google_callback'),
    path('auth/facebook/login/', facebook_login, name='facebook_login'),
    path('auth/line/login/', line_login, name='line_login'),
    path('register/', register_view, name='register'),
    path('register/quick/', quick_register_view, name='quick_register'),
    path('register/success/', registration_success_view, name='registration_success'),

    path('profile/', user_profile_view, name='profile'),
    path('profile/complete/', profile_completion_view, name='profile_complete'),
    path('profile/change-password/', change_password, name='change_password'),
    path('profile/set-password/', set_password, name='set_password'),
    path('profile/phone-update/', phone_profile_update_view, name='phone_profile_update'),

    path('product/<int:product_id>/', product_detail_view, name='product_detail'),
    path('product/<int:product_id>/quick-view/', quick_view_product, name='quick_view_product'),
    path('product/review/submit/', submit_review, name='submit_review'),
    path('product/review/delete/', delete_review, name='delete_review'),

    path('cart/', cart_view, name='cart'),
    path('cart/update/', update_cart_item, name='update_cart_item'),
    path('cart/remove/', remove_cart_item, name='remove_cart_item'),
    path('cart/totals/', cart_totals, name='cart_totals'),
    path('checkout/', checkout, name='checkout'),
    path('checkout/calculate-price/', calculate_checkout_price, name='calculate_checkout_price'),

    path('payment/<int:order_id>/', payment_view, name='payment'),
    path('payment/<int:order_id>/process/', process_payment, name='process_payment'),
    path('payment/<int:order_id>/success/', payment_success_view, name='payment_success'),
    path('payment/<int:order_id>/failed/', payment_failed_view, name='payment_failed'),
    path('payment/<int:order_id>/linepay/confirm/', linepay_confirm, name='linepay_confirm'),
    path('payment/<int:order_id>/linepay/cancel/', linepay_cancel, name='linepay_cancel'),

    path('orders/', order_list_view, name='order_list'),
    path('orders/<int:order_id>/', order_detail_view, name='order_detail'),
    path('orders/<int:order_id>/cancel/', cancel_order_view, name='cancel_order'),
    path('orders/<int:order_id>/confirm-receipt/', confirm_receipt_view, name='confirm_receipt'),

    path('wishlist/', wishlist_view, name='wishlist'),

    path('notifications/', notification_list_view, name='notification_list'),
    path('notifications/<int:notification_id>/', notification_detail_view, name='notification_detail'),
    path('notifications/<int:notification_id>/toggle-read/', notification_toggle_read, name='notification_toggle_read'),
    path('notifications/<int:notification_id>/delete/', notification_delete, name='notification_delete'),
    path('api/notifications/', notification_api, name='notification_api'),
    path('api/notifications/unread-count/', notification_unread_count_api, name='notification_unread_count_api'),
    path('api/notifications/mark-all-read/', notification_mark_all_read, name='notification_mark_all_read'),
    path('api/notifications/batch-action/', notification_batch_action, name='notification_batch_action'),

    path('ajax-login/', ajax_login, name='ajax_login'),
    path('check-username/', check_username_availability, name='check_username'),
    path('check-email/', check_email_availability, name='check_email'),
    path('suggest-usernames/', suggest_usernames, name='suggest_usernames'),
    path('validate-login/', validate_login_credentials, name='validate_login'),
    path('check-login/', check_login_status, name='check_login_status'),
    path('newsletter-subscribe/', newsletter_subscribe, name='newsletter_subscribe'),
    path('api/phone/send-code/', send_phone_verification_code, name='send_phone_verification_code'),
    path('api/phone/login/', phone_login, name='phone_login'),
    path('api/phone/verify-in-profile/', verify_phone_in_profile, name='verify_phone_in_profile'),

    path('api/cart/count/', cart_count_api, name='cart_count_api'),
    path('api/cart/add/', add_to_cart, name='api_add_to_cart'),
    path('api/wishlist/toggle/', toggle_wishlist, name='api_toggle_wishlist'),
    path('api/categories/', get_categories_api, name='categories_api'),

    path('goals/', goal_management_view, name='goal_management'),
    path('api/goals/update/', update_goal_view, name='update_goal'),
    path('api/goals/weight-log/', add_weight_log_view, name='add_weight_log'),
    path('api/goals/weight-log/data/', weight_log_api, name='weight_log_api'),
    path('api/foods/search/', food_search_api, name='food_search_api'),
    path('api/nutrition-log/add/', add_nutrition_log_view, name='add_nutrition_log'),
    path('api/nutrition-log/<int:log_id>/update/', update_nutrition_log_view, name='update_nutrition_log'),
    path('api/nutrition-log/<int:log_id>/delete/', delete_nutrition_log_view, name='delete_nutrition_log'),
    path('api/nutrition-log/', nutrition_log_api, name='nutrition_log_api'),

    path('articles/', articles_list_view, name='articles_list'),
    path('article/<slug:slug>/', article_detail_view, name='article_detail'),

    path('privacy/', privacy_policy_view, name='privacy_policy'),
    path('terms/', terms_of_service_view, name='terms_of_service'),
    path('delete-account/', delete_account_view, name='delete_account'),

    path('customer-service/shipping/', shipping_info_view, name='shipping_info'),
    path('customer-service/return/', return_policy_view, name='return_policy'),
    path('customer-service/faq/', faq_view, name='faq'),
    path('customer-service/contact/', contact_us_view, name='contact_us'),
]
