from django.test import SimpleTestCase
from django.urls import reverse


NAMED_URLS = [
    ('password_reset', {}, '/account/password-reset/'),
    ('password_reset_confirm', {'token': 'tok'}, '/account/password-reset/confirm/tok/'),
    ('verify_email', {'token': 'tok'}, '/account/verify-email/tok/'),
    ('resend_verification_email', {}, '/account/resend-verification-email/'),
    ('verify_email_change', {'token': 'tok'}, '/account/verify-email-change/tok/'),
    ('social_complete', {'backend': 'google-oauth2'}, '/auth/complete/google-oauth2/'),
    ('social_auth_error', {}, '/auth/error/'),
    ('home', {}, '/'),
    ('products', {}, '/products/'),
    ('search', {}, '/search/'),
    ('login', {}, '/login/'),
    ('logout', {}, '/logout/'),
    ('google_login', {}, '/auth/google/login/'),
    ('google_callback', {}, '/auth/google/callback/'),
    ('facebook_login', {}, '/auth/facebook/login/'),
    ('line_login', {}, '/auth/line/login/'),
    ('register', {}, '/register/'),
    ('quick_register', {}, '/register/quick/'),
    ('registration_success', {}, '/register/success/'),
    ('profile', {}, '/profile/'),
    ('profile_complete', {}, '/profile/complete/'),
    ('change_password', {}, '/profile/change-password/'),
    ('set_password', {}, '/profile/set-password/'),
    ('phone_profile_update', {}, '/profile/phone-update/'),
    ('product_detail', {'product_id': 1}, '/product/1/'),
    ('quick_view_product', {'product_id': 1}, '/product/1/quick-view/'),
    ('submit_review', {}, '/product/review/submit/'),
    ('delete_review', {}, '/product/review/delete/'),
    ('cart', {}, '/cart/'),
    ('update_cart_item', {}, '/cart/update/'),
    ('remove_cart_item', {}, '/cart/remove/'),
    ('cart_totals', {}, '/cart/totals/'),
    ('checkout', {}, '/checkout/'),
    ('calculate_checkout_price', {}, '/checkout/calculate-price/'),
    ('payment', {'order_id': 1}, '/payment/1/'),
    ('process_payment', {'order_id': 1}, '/payment/1/process/'),
    ('payment_success', {'order_id': 1}, '/payment/1/success/'),
    ('payment_failed', {'order_id': 1}, '/payment/1/failed/'),
    ('linepay_confirm', {'order_id': 1}, '/payment/1/linepay/confirm/'),
    ('linepay_cancel', {'order_id': 1}, '/payment/1/linepay/cancel/'),
    ('ecpay_checkout', {'order_id': 1}, '/payment/1/ecpay/checkout/'),
    ('ecpay_return', {}, '/payment/ecpay/return/'),
    ('ecpay_result', {'order_id': 1}, '/payment/1/ecpay/result/'),
    ('order_list', {}, '/orders/'),
    ('order_detail', {'order_id': 1}, '/orders/1/'),
    ('cancel_order', {'order_id': 1}, '/orders/1/cancel/'),
    ('confirm_receipt', {'order_id': 1}, '/orders/1/confirm-receipt/'),
    ('request_return', {'order_id': 1}, '/orders/1/return/'),
    ('cancel_return', {'order_id': 1, 'return_id': 2}, '/orders/1/return/2/cancel/'),
    ('reorder', {'order_id': 1}, '/orders/1/reorder/'),
    ('wishlist', {}, '/wishlist/'),
    ('wishlist_add_all_to_cart', {}, '/wishlist/add-all-to-cart/'),
    ('notification_list', {}, '/notifications/'),
    ('notification_detail', {'notification_id': 1}, '/notifications/1/'),
    ('notification_toggle_read', {'notification_id': 1}, '/notifications/1/toggle-read/'),
    ('notification_delete', {'notification_id': 1}, '/notifications/1/delete/'),
    ('notification_api', {}, '/api/notifications/'),
    ('notification_unread_count_api', {}, '/api/notifications/unread-count/'),
    ('notification_mark_all_read', {}, '/api/notifications/mark-all-read/'),
    ('notification_batch_action', {}, '/api/notifications/batch-action/'),
    ('ajax_login', {}, '/ajax-login/'),
    ('check_username', {}, '/check-username/'),
    ('check_email', {}, '/check-email/'),
    ('suggest_usernames', {}, '/suggest-usernames/'),
    ('validate_login', {}, '/validate-login/'),
    ('check_login_status', {}, '/check-login/'),
    ('newsletter_subscribe', {}, '/newsletter-subscribe/'),
    ('send_phone_verification_code', {}, '/api/phone/send-code/'),
    ('phone_login', {}, '/api/phone/login/'),
    ('verify_phone_in_profile', {}, '/api/phone/verify-in-profile/'),
    ('cart_count_api', {}, '/api/cart/count/'),
    ('api_add_to_cart', {}, '/api/cart/add/'),
    ('api_toggle_wishlist', {}, '/api/wishlist/toggle/'),
    ('categories_api', {}, '/api/categories/'),
    ('goal_management', {}, '/goals/'),
    ('update_goal', {}, '/api/goals/update/'),
    ('add_weight_log', {}, '/api/goals/weight-log/'),
    ('weight_log_api', {}, '/api/goals/weight-log/data/'),
    ('food_search_api', {}, '/api/foods/search/'),
    ('add_nutrition_log', {}, '/api/nutrition-log/add/'),
    ('update_nutrition_log', {'log_id': 1}, '/api/nutrition-log/1/update/'),
    ('delete_nutrition_log', {'log_id': 1}, '/api/nutrition-log/1/delete/'),
    ('nutrition_log_api', {}, '/api/nutrition-log/'),
    ('add_custom_food', {}, '/api/foods/custom/'),
    ('add_workout_log', {}, '/api/workouts/add/'),
    ('add_water_log', {}, '/api/water/add/'),
    ('log_product_nutrition', {}, '/api/products/log-nutrition/'),
    ('health_export', {}, '/goals/export/'),
    ('bmi_calculator', {}, '/health/calculator/'),
    ('address_book', {}, '/profile/addresses/'),
    ('address_set_default', {'address_id': 1}, '/profile/addresses/1/default/'),
    ('address_delete', {'address_id': 1}, '/profile/addresses/1/delete/'),
    ('address_json_api', {}, '/api/addresses/'),
    ('articles_list', {}, '/articles/'),
    ('article_detail', {'slug': 'sample'}, '/article/sample/'),
    ('privacy_policy', {}, '/privacy/'),
    ('terms_of_service', {}, '/terms/'),
    ('delete_account', {}, '/delete-account/'),
    ('shipping_info', {}, '/customer-service/shipping/'),
    ('return_policy', {}, '/customer-service/return/'),
    ('faq', {}, '/customer-service/faq/'),
    ('contact_us', {}, '/customer-service/contact/'),
]


class NamedUrlTests(SimpleTestCase):
    def test_named_urls_match_existing_paths(self):
        self.assertEqual(len(NAMED_URLS), 102)
        for name, kwargs, expected in NAMED_URLS:
            with self.subTest(name=name):
                self.assertEqual(reverse(name, kwargs=kwargs), expected)
