"""
Django settings for GoodJian project.

Generated by 'django-admin startproject' using Django 5.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os

from django.core.exceptions import ImproperlyConfigured

# GoodJian/settings/base.py → 專案根目錄
BASE_DIR = Path(__file__).resolve().parent.parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

DEBUG = os.getenv('DEBUG', 'False').lower() == 'true'

SECRET_KEY = os.getenv('SECRET_KEY', '').strip()
if not SECRET_KEY:
    if DEBUG:
        SECRET_KEY = 'django-insecure-local-dev-only'
    else:
        raise ImproperlyConfigured('SECRET_KEY must be set in the environment when DEBUG is False.')

SITE_DOMAIN = os.getenv('SITE_DOMAIN', 'localhost:8000')

# 從環境變數讀取允許的主機（生產環境必須設置！）
# 處理逗號分隔的值，並去除每個值的前後空格
allowed_hosts_str = os.getenv('ALLOWED_HOSTS', '').strip()
ALLOWED_HOSTS = [host.strip() for host in allowed_hosts_str.split(',') if host.strip()] if allowed_hosts_str else []


def _csrf_trusted_origins():
    raw = os.getenv('CSRF_TRUSTED_ORIGINS', '').strip()
    if raw:
        return [origin.strip() for origin in raw.split(',') if origin.strip()]
    scheme = 'http' if DEBUG else 'https'
    origins = []
    if DEBUG:
        origins.extend(['http://localhost:8000', 'http://127.0.0.1:8000'])
    hosts = []
    if SITE_DOMAIN:
        hosts.append(SITE_DOMAIN.split('/')[0].strip())
    hosts.extend(ALLOWED_HOSTS)
    for host in hosts:
        if not host or host in ('*',):
            continue
        origins.append(f'{scheme}://{host}')
        if host.startswith('www.'):
            origins.append(f'{scheme}://{host[4:]}')
        elif '.' in host and not host.startswith('localhost') and not host.replace('.', '').isdigit():
            origins.append(f'{scheme}://www.{host}')
    seen = set()
    unique = []
    for origin in origins:
        if origin not in seen:
            seen.add(origin)
            unique.append(origin)
    return unique


CSRF_TRUSTED_ORIGINS = _csrf_trusted_origins()


# Application definition

INSTALLED_APPS = [
    'plus',
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_summernote',  # 富文本編輯器
    'social_django',  # Google OAuth 登入
]

JAZZMIN_SETTINGS = {
    'site_title': '好健健管理系統',
    'site_header': '好健健 GoodJian Plus',
    'site_brand': '好健健 GoodJian Plus',
    'site_logo': 'img/common/Logo.png',
    'login_logo': 'img/common/Logo.png',
    'site_logo_classes': 'img-circle brand-image opacity-75 shadow',
    'welcome_sign': '歡迎使用好健健管理後台',
    'copyright': 'GoodJian Plus',
    'custom_css': 'css/admin-theme-toggle.css',
    'custom_js': 'js/admin-theme-toggle.js',
    'show_sidebar': True,
    'navigation_expanded': True,
    'show_theme_chooser': False,
    'show_ui_builder': False,
    'hide_apps': [
        'django_summernote',
        'social_django',
    ],
    'hide_models': [
        'plus.category',
        'plus.brand',
        'plus.product',
        'plus.productreview',
        'plus.cart',
        'plus.order',
        'plus.returnrequest',
        'plus.coupon',
        'plus.wishlist',
        'plus.shippingmethod',
        'plus.shippingaddress',
        'plus.articlecategory',
        'plus.article',
        'plus.articleimage',
        'plus.customuser',
        'plus.emailverificationtoken',
        'plus.notification',
        'plus.newslettersubscriber',
        'plus.food',
        'plus.usergoal',
        'plus.weightlog',
        'plus.nutritionlog',
        'plus.dailynutritiontarget',
        'plus.workoutlog',
        'plus.waterlog',
        'plus.dailyhealthlog',
        'plus.sitesettings',
    ],
    'order_with_respect_to': [
        '商品與目錄',
        '訂單與物流',
        '內容管理',
        '會員與通知',
        '健康與營養',
        '系統設定',
        'plus',
    ],
    'custom_links': {
        '商品與目錄': [
            {'model': 'plus.Category'},
            {'model': 'plus.Brand'},
            {'model': 'plus.Product'},
            {'model': 'plus.ProductReview'},
        ],
        '訂單與物流': [
            {'model': 'plus.Cart'},
            {'model': 'plus.Order'},
            {'model': 'plus.ReturnRequest'},
            {'model': 'plus.Coupon'},
            {'model': 'plus.Wishlist'},
            {'model': 'plus.ShippingMethod'},
            {'model': 'plus.ShippingAddress'},
        ],
        '內容管理': [
            {'model': 'plus.ArticleCategory'},
            {'model': 'plus.Article'},
            {'model': 'plus.ArticleImage'},
        ],
        '會員與通知': [
            {'model': 'plus.CustomUser'},
            {'model': 'plus.EmailVerificationToken'},
            {'model': 'plus.Notification'},
            {'model': 'plus.NewsletterSubscriber'},
        ],
        '健康與營養': [
            {'model': 'plus.Food'},
            {'model': 'plus.UserGoal'},
            {'model': 'plus.WeightLog'},
            {'model': 'plus.NutritionLog'},
            {'model': 'plus.DailyNutritionTarget'},
            {'model': 'plus.WorkoutLog'},
            {'model': 'plus.WaterLog'},
            {'model': 'plus.DailyHealthLog'},
        ],
        '系統設定': [
            {'model': 'plus.SiteSettings'},
        ],
    },
    'search_model': [
        'plus.Product',
        'plus.Order',
        'plus.CustomUser',
    ],
    'topmenu_links': [
        {'name': '瀏覽前台', 'url': '/', 'new_window': True},
    ],
    'usermenu_links': [
        {'name': '最近的動作', 'url': 'admin:recent-actions', 'icon': 'fas fa-clock-rotate-left'},
    ],
    'icons': {
        'plus': 'fas fa-puzzle-piece',
        '商品與目錄': 'fas fa-boxes-stacked',
        '訂單與物流': 'fas fa-truck-fast',
        '內容管理': 'fas fa-newspaper',
        '會員與通知': 'fas fa-users',
        '健康與營養': 'fas fa-heart-pulse',
        '系統設定': 'fas fa-sliders',
        'plus.product': 'fas fa-dumbbell',
        'plus.order': 'fas fa-receipt',
        'plus.customuser': 'fas fa-users',
        'plus.article': 'fas fa-newspaper',
        'plus.food': 'fas fa-utensils',
    },
}

JAZZMIN_UI_TWEAKS = {
    'theme': 'united',
    'default_theme_mode': 'light',
    'navbar_small_text': False,
    'sidebar_nav_small_text': False,
    'sidebar_disable_expand': False,
    'sidebar_fixed': True,
    'navbar_fixed': True,
    'footer_fixed': False,
    'button_classes': {
        'primary': 'btn-success',
        'secondary': 'btn-outline-secondary',
        'info': 'btn-info',
        'warning': 'btn-warning',
        'danger': 'btn-danger',
        'success': 'btn-success',
    },
}

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'social_django.middleware.SocialAuthExceptionMiddleware',  # 處理社交登入異常（必須在最後）
]

# 加入這一行 - 指定使用自定義用戶模型
AUTH_USER_MODEL = 'plus.CustomUser'

# 認證後端設定（支援 Google、Facebook 和 LINE OAuth）
AUTHENTICATION_BACKENDS = (
    'social_core.backends.google.GoogleOAuth2',  # Google OAuth
    'social_core.backends.facebook.FacebookOAuth2',  # Facebook OAuth
    'social_core.backends.line.LineOAuth2',  # LINE OAuth
    'django.contrib.auth.backends.ModelBackend',  # Django 預設認證
)

# 登入相關設定
LOGIN_URL = '/login/'
LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/'

# Social Auth 登入後重定向
SOCIAL_AUTH_LOGIN_REDIRECT_URL = '/'
SOCIAL_AUTH_NEW_USER_REDIRECT_URL = '/'
SOCIAL_AUTH_LOGIN_ERROR_URL = '/auth/error/'

# Google OAuth 設定
SOCIAL_AUTH_GOOGLE_OAUTH2_KEY = os.getenv('GOOGLE_OAUTH2_CLIENT_ID', '')
SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET = os.getenv('GOOGLE_OAUTH2_CLIENT_SECRET', '')

# Social Auth 設定
SOCIAL_AUTH_GOOGLE_OAUTH2_SCOPE = [
    'https://www.googleapis.com/auth/userinfo.email',
    'https://www.googleapis.com/auth/userinfo.profile',
]

# Facebook OAuth 設定
SOCIAL_AUTH_FACEBOOK_KEY = os.getenv('FACEBOOK_APP_ID', '')
SOCIAL_AUTH_FACEBOOK_SECRET = os.getenv('FACEBOOK_APP_SECRET', '')
SOCIAL_AUTH_FACEBOOK_SCOPE = ['email', 'public_profile']
SOCIAL_AUTH_FACEBOOK_PROFILE_EXTRA_PARAMS = {
    'fields': 'id, name, email, first_name, last_name'
}

# LINE OAuth 設定
SOCIAL_AUTH_LINE_KEY = os.getenv('LINE_CHANNEL_ID', '')
SOCIAL_AUTH_LINE_SECRET = os.getenv('LINE_CHANNEL_SECRET', '')
SOCIAL_AUTH_LINE_SCOPE = ['profile', 'openid', 'email']

# 用戶模型欄位映射
SOCIAL_AUTH_USER_MODEL = 'plus.CustomUser'
SOCIAL_AUTH_USERNAME_IS_FULL_EMAIL = False

# 當用戶通過 Google 登入時，自動創建用戶
SOCIAL_AUTH_CREATE_USERS = True
SOCIAL_AUTH_AUTO_LOGIN = True

# 管道設定（處理用戶資料）
SOCIAL_AUTH_PIPELINE = (
    'social_core.pipeline.social_auth.social_details',
    'social_core.pipeline.social_auth.social_uid',
    'social_core.pipeline.social_auth.auth_allowed',
    'social_core.pipeline.social_auth.social_user',
    'plus.views.associate_by_email',  # 自定義：如果 email 已存在，關聯到現有用戶
    'social_core.pipeline.user.get_username',
    'social_core.pipeline.user.create_user',
    'social_core.pipeline.social_auth.associate_user',
    'social_core.pipeline.social_auth.load_extra_data',
    'social_core.pipeline.user.user_details',  # 這步會自動填入 first_name 和 last_name
    'plus.views.social_auth_pipeline',  # 自定義管道處理（處理 Google 和 Facebook 的用戶資料）
)

ROOT_URLCONF = 'GoodJian.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'builtins': [
                'plus.templatetags.currency_filters',
            ],
            'context_processors': [
                'django.template.context_processors.debug',  
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'plus.context_processors.site_settings',
            ],
        },
    },
]

WSGI_APPLICATION = 'GoodJian.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# ========== 資料庫設定 ==========
# DB_ENGINE=sqlite 用於地端開發，DB_ENGINE=mysql 用於生產環境
DB_ENGINE = os.getenv('DB_ENGINE', 'sqlite').lower()

if DB_ENGINE == 'mysql':
    import pymysql
    pymysql.install_as_MySQLdb()

    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.mysql',
            'NAME': os.getenv('DB_NAME', 'goodjian'),
            'USER': os.getenv('DB_USER', 'root'),
            'PASSWORD': os.getenv('DB_PASSWORD', ''),  # 生產環境必須使用環境變數
            'HOST': os.getenv('DB_HOST', 'localhost'),
            'PORT': os.getenv('DB_PORT', '3306'),
            'OPTIONS': {
                'charset': 'utf8mb4',
                'init_command': "SET sql_mode='STRICT_TRANS_TABLES'",
            },
        }
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': os.getenv('SQLITE_NAME', os.path.join(BASE_DIR, 'db.sqlite3')),
        }
    }

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'zh-hant' #修改的地方

TIME_ZONE = 'Asia/Taipei' #修改的地方

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'), 
] #新增的地方
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')  # 收集靜態文件的目錄

# 靜態文件版本號（用於強制刷新緩存）
# 每次更新 CSS/JS 時，請更新此版本號
STATIC_VERSION = os.getenv('STATIC_VERSION', '1.0.6')

# 在檔案最後加入
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'goodjian-local',
        'TIMEOUT': 300,
    }
}

# ========== Summernote 富文本編輯器設定 ==========
SUMMERNOTE_THEME = 'bs5'  # 使用 Bootstrap 5 主題

SUMMERNOTE_CONFIG = {
    # 編輯器尺寸
    'width': '100%',
    'height': '500',
    'iframe': True,  # 使用 iframe 模式
    
    # 工具欄設定
    'toolbar': [
        ['style', ['style']],
        ['font', ['bold', 'italic', 'underline', 'clear']],
        ['fontname', ['fontname']],
        ['fontsize', ['fontsize']],
        ['color', ['color']],
        ['para', ['ul', 'ol', 'paragraph']],
        ['table', ['table']],
        ['insert', ['link', 'picture', 'video']],
        ['view', ['fullscreen', 'codeview', 'help']],
    ],
    
    # 允許的 HTML 標籤
    'allowedTags': [
        'p', 'br', 'strong', 'em', 'u', 's', 'h1', 'h2', 'h3', 'h4', 'h5', 'h6',
        'ul', 'ol', 'li', 'blockquote', 'pre', 'code', 'a', 'img', 'table',
        'thead', 'tbody', 'tr', 'th', 'td', 'div', 'span', 'hr'
    ],
    
    # 允許的 HTML 屬性
    'allowedAttributes': {
        '*': ['class', 'id', 'style'],
        'a': ['href', 'target', 'title'],
        'img': ['src', 'alt', 'width', 'height', 'title'],
        'table': ['border', 'cellpadding', 'cellspacing'],
    },
    
    # 上傳圖片設定
    'attachment_filesize_limit': 5 * 1024 * 1024,  # 5MB
    'attachment_require_authentication': True,
    
    # 語言設定
    'lang': 'zh-TW',
    
    # 其他設定
    'codemirror': {
        'mode': 'htmlmixed',
        'lineNumbers': 'true',
        'theme': 'monokai',
    },
}

# ========== 郵件設定 ==========
# 從環境變數讀取郵件配置
EMAIL_BACKEND = os.getenv('EMAIL_BACKEND', 'django.core.mail.backends.smtp.EmailBackend')
EMAIL_HOST = os.getenv('EMAIL_HOST', 'smtp.gmail.com')  # 使用 Gmail SMTP，可根據需要修改
EMAIL_PORT = int(os.getenv('EMAIL_PORT', '587'))
EMAIL_USE_TLS = os.getenv('EMAIL_USE_TLS', 'True').lower() == 'true'
EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER', '')  # 從環境變數讀取郵件地址
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD', '')  # 從環境變數讀取郵件密碼或應用程式密碼
DEFAULT_FROM_EMAIL = os.getenv('DEFAULT_FROM_EMAIL', '好健健 GoodJian Plus <noreply@goodjianplus.com>')

# ========== 日誌設定 ==========
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
            'style': '{',
            'datefmt': '%Y-%m-%d %H:%M:%S',
        },
        'simple': {
            'format': '{levelname} {message}',
            'style': '{',
        },
    },
    'filters': {
        'require_debug_false': {
            '()': 'django.utils.log.RequireDebugFalse',
        },
    },
    'handlers': {
        'file': {
            'level': 'INFO',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': os.path.join(BASE_DIR, 'logs', 'django.log'),
            'maxBytes': 1024 * 1024 * 10,  # 10MB
            'backupCount': 5,
            'formatter': 'verbose',
        },
        'error_file': {
            'level': 'ERROR',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': os.path.join(BASE_DIR, 'logs', 'django_error.log'),
            'maxBytes': 1024 * 1024 * 10,  # 10MB
            'backupCount': 5,
            'formatter': 'verbose',
        },
        'console': {
            'level': 'DEBUG' if DEBUG else 'INFO',
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
        'mail_admins': {
            'level': 'ERROR',
            'class': 'django.utils.log.AdminEmailHandler',
            'filters': ['require_debug_false'],
        },
    },
    'root': {
        'handlers': ['console', 'file'],
        'level': 'INFO',
    },
    'loggers': {
        'django': {
            'handlers': ['console', 'file', 'error_file'],
            'level': 'INFO',
            'propagate': False,
        },
        'django.request': {
            'handlers': ['error_file', 'mail_admins'],
            'level': 'ERROR',
            'propagate': False,
        },
        'plus': {
            'handlers': ['console', 'file', 'error_file'],
            'level': 'INFO',
            'propagate': False,
        },
    },
}

# 確保 logs 目錄存在
LOGS_DIR = os.path.join(BASE_DIR, 'logs')
if not os.path.exists(LOGS_DIR):
    os.makedirs(LOGS_DIR)

# ========== Session 設定 ==========
# 設定 session 過期時間為 15 分鐘（與前端 JavaScript 同步）
SESSION_COOKIE_AGE = 15 * 60  # 15 分鐘（秒）
SESSION_SAVE_EVERY_REQUEST = True  # 每次請求都保存 session，延長過期時間
SESSION_EXPIRE_AT_BROWSER_CLOSE = False  # 瀏覽器關閉時不立即過期
SESSION_COOKIE_SECURE = not DEBUG  # 生產環境使用 HTTPS
SESSION_COOKIE_HTTPONLY = True  # 防止 XSS 攻擊

# ========== LINE Pay 設定 ==========
# 從環境變數讀取 LINE Pay 配置
LINE_PAY_CHANNEL_ID = os.getenv('LINE_PAY_CHANNEL_ID', '')
LINE_PAY_CHANNEL_SECRET = os.getenv('LINE_PAY_CHANNEL_SECRET', '')
LINE_PAY_SANDBOX = os.getenv('LINE_PAY_SANDBOX', 'True').lower() == 'true'  # 預設使用沙盒環境

# ========== 綠界科技 ECPay ==========
ECPAY_MERCHANT_ID = os.getenv('ECPAY_MERCHANT_ID', '')
ECPAY_HASH_KEY = os.getenv('ECPAY_HASH_KEY', '')
ECPAY_HASH_IV = os.getenv('ECPAY_HASH_IV', '')
ECPAY_SANDBOX = os.getenv('ECPAY_SANDBOX', 'True').lower() == 'true'

# ========== OpenAI（後台商品文案，可選） ==========
OPENAI_API_KEY = os.getenv('OPENAI_API_KEY', '')
OPENAI_MODEL = os.getenv('OPENAI_MODEL', 'gpt-4o-mini')

# ========== HTTPS 安全設定 ==========
# 生產環境 HTTPS 設定（當 DEBUG=False 時啟用）
if not DEBUG:
    # 強制所有請求使用 HTTPS
    SECURE_SSL_REDIRECT = True
    
    # Cookie 安全設定
    SESSION_COOKIE_SECURE = True  # Session cookie 只在 HTTPS 傳輸
    CSRF_COOKIE_SECURE = True  # CSRF cookie 只在 HTTPS 傳輸
    
    # HSTS (HTTP Strict Transport Security)
    SECURE_HSTS_SECONDS = 31536000  # 1 年（秒）
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True  # 包含子域名
    SECURE_HSTS_PRELOAD = True  # 允許加入瀏覽器 HSTS 預載列表
    
    # 信任代理標頭（Nginx 反向代理）
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    
    # 其他安全標頭
    SECURE_BROWSER_XSS_FILTER = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    X_FRAME_OPTIONS = 'DENY'

SENTRY_DSN = os.getenv('SENTRY_DSN', '').strip()
if SENTRY_DSN:
    try:
        import sentry_sdk
        from sentry_sdk.integrations.django import DjangoIntegration
        sentry_sdk.init(
            dsn=SENTRY_DSN,
            integrations=[DjangoIntegration()],
            send_default_pii=False,
            traces_sample_rate=0.1,
        )
    except ImportError:
        pass
