# Generated by Django 5.2.8 on 2025-12-14 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plus', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productreview',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='更新時間'),
        ),
    ]
