# Generated by Django 5.2.8 on 2025-12-14 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plus', '0002_productreview_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(default='cod', max_length=50, verbose_name='支付方式'),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_transaction_id',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='支付交易編號'),
        ),
    ]
