# Generated by Django 5.2.8 on 2025-12-15 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plus', '0003_order_payment_method_order_payment_transaction_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='homepage_slogan',
            field=models.CharField(default='健康生活觸手可及', max_length=200, verbose_name='首頁標語'),
        ),
    ]
