# Generated by Django 5.2.8 on 2025-12-16 19:36

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plus', '0004_sitesettings_homepage_slogan'),
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='食物名稱')),
                ('category', models.CharField(choices=[('grains', '穀物類'), ('vegetables', '蔬菜類'), ('fruits', '水果類'), ('meat', '肉類'), ('seafood', '海鮮類'), ('dairy', '乳製品'), ('nuts', '堅果類'), ('beverages', '飲品'), ('snacks', '零食'), ('others', '其他')], max_length=20, verbose_name='分類')),
                ('serving_size', models.CharField(default='100g', max_length=50, verbose_name='份量')),
                ('calories', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='熱量（大卡）')),
                ('protein', models.DecimalField(decimal_places=2, default=0, max_digits=7, verbose_name='蛋白質（g）')),
                ('carbs', models.DecimalField(decimal_places=2, default=0, max_digits=7, verbose_name='碳水化合物（g）')),
                ('fat', models.DecimalField(decimal_places=2, default=0, max_digits=7, verbose_name='脂肪（g）')),
                ('fiber', models.DecimalField(decimal_places=2, default=0, max_digits=7, verbose_name='纖維（g）')),
                ('sugar', models.DecimalField(decimal_places=2, default=0, max_digits=7, verbose_name='糖（g）')),
                ('sodium', models.DecimalField(decimal_places=2, default=0, max_digits=7, verbose_name='鈉（mg）')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否啟用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
            ],
            options={
                'verbose_name': '食物營養資料',
                'verbose_name_plural': '食物營養資料管理',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='NutritionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, default=1, max_digits=7, verbose_name='數量（份）')),
                ('meal_type', models.CharField(choices=[('breakfast', '早餐'), ('lunch', '午餐'), ('dinner', '晚餐'), ('snack', '點心')], max_length=20, verbose_name='餐點類型')),
                ('logged_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='記錄時間')),
                ('notes', models.TextField(blank=True, verbose_name='備註')),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plus.food', verbose_name='食物')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nutrition_logs', to=settings.AUTH_USER_MODEL, verbose_name='用戶')),
            ],
            options={
                'verbose_name': '營養記錄',
                'verbose_name_plural': '營養記錄管理',
                'ordering': ['-logged_at'],
            },
        ),
        migrations.CreateModel(
            name='UserGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal_type', models.CharField(choices=[('lose_weight', '減重'), ('maintain', '維持體重'), ('gain_weight', '增重'), ('build_muscle', '增肌')], default='maintain', max_length=20, verbose_name='目標類型')),
                ('target_weight', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='目標體重（kg）')),
                ('current_weight', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='目前體重（kg）')),
                ('height', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='身高（cm）')),
                ('age', models.PositiveIntegerField(blank=True, null=True, verbose_name='年齡')),
                ('gender', models.CharField(blank=True, choices=[('male', '男性'), ('female', '女性')], max_length=10, null=True, verbose_name='性別')),
                ('activity_level', models.CharField(choices=[('sedentary', '久坐不動（幾乎不運動）'), ('light', '輕度活動（每週1-3天運動）'), ('moderate', '中度活動（每週3-5天運動）'), ('active', '高度活動（每週6-7天運動）'), ('very_active', '極高度活動（每天劇烈運動）')], default='sedentary', max_length=20, verbose_name='活動強度')),
                ('bmr', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='基礎代謝率（BMR）')),
                ('tdee', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='總每日能量消耗（TDEE）')),
                ('target_calories', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='目標熱量（大卡）')),
                ('target_protein', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='目標蛋白質（g）')),
                ('target_carbs', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='目標碳水化合物（g）')),
                ('target_fat', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='目標脂肪（g）')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='goal', to=settings.AUTH_USER_MODEL, verbose_name='用戶')),
            ],
            options={
                'verbose_name': '用戶目標',
                'verbose_name_plural': '用戶目標管理',
            },
        ),
        migrations.CreateModel(
            name='WeightLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='體重（kg）')),
                ('body_fat', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='體脂率（%）')),
                ('muscle_mass', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='肌肉量（kg）')),
                ('notes', models.TextField(blank=True, verbose_name='備註')),
                ('recorded_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='記錄時間')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weight_logs', to=settings.AUTH_USER_MODEL, verbose_name='用戶')),
            ],
            options={
                'verbose_name': '體重記錄',
                'verbose_name_plural': '體重記錄管理',
                'ordering': ['-recorded_at'],
            },
        ),
    ]
