# Generated by Django 5.2.8 on 2025-12-16 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plus', '0005_food_nutritionlog_usergoal_weightlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='usergoal',
            name='current_bone_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='目前骨骼比例（%）'),
        ),
        migrations.AddField(
            model_name='usergoal',
            name='current_fat_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='目前脂肪比例（%）'),
        ),
        migrations.AddField(
            model_name='usergoal',
            name='current_muscle_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='目前肌肉比例（%）'),
        ),
        migrations.AddField(
            model_name='usergoal',
            name='current_water_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='目前水分比例（%）'),
        ),
        migrations.AddField(
            model_name='usergoal',
            name='target_bone_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='目標骨骼比例（%）'),
        ),
        migrations.AddField(
            model_name='usergoal',
            name='target_fat_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='目標脂肪比例（%）'),
        ),
        migrations.AddField(
            model_name='usergoal',
            name='target_muscle_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='目標肌肉比例（%）'),
        ),
        migrations.AddField(
            model_name='usergoal',
            name='target_water_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='目標水分比例（%）'),
        ),
        migrations.AddField(
            model_name='weightlog',
            name='bone_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='骨骼比例（%）'),
        ),
        migrations.AddField(
            model_name='weightlog',
            name='fat_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='脂肪比例（%）'),
        ),
        migrations.AddField(
            model_name='weightlog',
            name='muscle_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='肌肉比例（%）'),
        ),
        migrations.AddField(
            model_name='weightlog',
            name='water_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='水分比例（%）'),
        ),
    ]
