# Generated by Django 5.2.8 on 2025-12-17 19:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plus', '0006_usergoal_current_bone_percentage_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyNutritionTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_date', models.DateField(verbose_name='目標日期')),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='當天體重（kg）')),
                ('height', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='身高（cm）')),
                ('age', models.PositiveIntegerField(blank=True, null=True, verbose_name='年齡')),
                ('gender', models.CharField(blank=True, choices=[('male', '男性'), ('female', '女性')], max_length=10, null=True, verbose_name='性別')),
                ('activity_level', models.CharField(choices=[('sedentary', '久坐不動（幾乎不運動）'), ('light', '輕度活動（每週1-3天運動）'), ('moderate', '中度活動（每週3-5天運動）'), ('active', '高度活動（每週6-7天運動）'), ('very_active', '極高度活動（每天劇烈運動）')], default='sedentary', max_length=20, verbose_name='活動強度')),
                ('goal_type', models.CharField(choices=[('lose_weight', '減重'), ('maintain', '維持體重'), ('gain_weight', '增重'), ('build_muscle', '增肌')], default='maintain', max_length=20, verbose_name='目標類型')),
                ('target_calories', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='目標熱量（大卡）')),
                ('target_protein', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='目標蛋白質（g）')),
                ('target_carbs', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='目標碳水化合物（g）')),
                ('target_fat', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='目標脂肪（g）')),
                ('bmr', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='基礎代謝率（BMR）')),
                ('tdee', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='總每日能量消耗（TDEE）')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_nutrition_targets', to=settings.AUTH_USER_MODEL, verbose_name='用戶')),
            ],
            options={
                'verbose_name': '每日營養目標',
                'verbose_name_plural': '每日營養目標管理',
                'ordering': ['-target_date'],
                'indexes': [models.Index(fields=['user', 'target_date'], name='plus_dailyn_user_id_5791ff_idx')],
                'unique_together': {('user', 'target_date')},
            },
        ),
    ]
