# Generated by Django 5.2.8 on 2025-12-17 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plus', '0008_alter_userprofile_height_alter_userprofile_weight'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usergoal',
            name='current_weight',
        ),
        migrations.RemoveField(
            model_name='usergoal',
            name='height',
        ),
    ]
