# Generated by Django 5.2.8 on 2025-12-18 18:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plus', '0009_remove_usergoal_current_weight_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='分類名稱')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='URL標識')),
                ('description', models.TextField(blank=True, verbose_name='分類描述')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否啟用')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='排序')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
            ],
            options={
                'verbose_name': '文章分類',
                'verbose_name_plural': '文章分類管理',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='文章標題')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='URL標識')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='articles/covers/', verbose_name='封面圖片')),
                ('content', models.TextField(verbose_name='文章內容（HTML）')),
                ('excerpt', models.TextField(blank=True, max_length=500, verbose_name='文章摘要')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('published', '已發佈'), ('archived', '已歸檔')], default='draft', max_length=20, verbose_name='文章狀態')),
                ('is_featured', models.BooleanField(default=False, verbose_name='是否為精選文章')),
                ('view_count', models.PositiveIntegerField(default=0, verbose_name='瀏覽次數')),
                ('meta_title', models.CharField(blank=True, max_length=100, verbose_name='SEO標題')),
                ('meta_description', models.CharField(blank=True, max_length=160, verbose_name='SEO描述')),
                ('meta_keywords', models.CharField(blank=True, max_length=200, verbose_name='SEO關鍵字')),
                ('author_name', models.CharField(blank=True, max_length=100, verbose_name='作者名稱（手動輸入）')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='發佈時間')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='作者')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='plus.articlecategory', verbose_name='文章分類')),
            ],
            options={
                'verbose_name': '健康專欄文章',
                'verbose_name_plural': '健康專欄文章管理',
                'ordering': ['-published_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ArticleImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='articles/images/', verbose_name='圖片')),
                ('alt_text', models.CharField(blank=True, max_length=200, verbose_name='替代文字')),
                ('caption', models.CharField(blank=True, max_length=200, verbose_name='圖片說明')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='排序')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='plus.article', verbose_name='文章')),
            ],
            options={
                'verbose_name': '文章圖片',
                'verbose_name_plural': '文章圖片管理',
                'ordering': ['sort_order', '-created_at'],
            },
        ),
    ]
