# Generated by Django 5.2.8 on 2025-12-23 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plus', '0010_articlecategory_article_articleimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('order', '訂單通知'), ('promotion', '促銷通知'), ('system', '系統通知'), ('review', '評價通知'), ('cart', '購物車通知'), ('wishlist', '收藏通知'), ('goal', '目標通知'), ('stock', '庫存通知')], max_length=20, verbose_name='通知類型'),
        ),
    ]
