# Generated by Django 5.2.8 on 2025-12-26 18:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plus', '0011_alter_notification_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailVerificationToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=64, unique=True, verbose_name='驗證碼')),
                ('token_type', models.CharField(choices=[('email_verification', '郵件驗證'), ('password_reset', '密碼重設')], default='email_verification', max_length=20, verbose_name='Token 類型')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('expires_at', models.DateTimeField(verbose_name='過期時間')),
                ('is_used', models.BooleanField(default=False, verbose_name='是否已使用')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_verification_tokens', to=settings.AUTH_USER_MODEL, verbose_name='用戶')),
            ],
            options={
                'verbose_name': '郵件驗證 Token',
                'verbose_name_plural': '郵件驗證 Token 管理',
                'ordering': ['-created_at'],
            },
        ),
    ]
