# Generated by Django 5.2.8 on 2025-12-29 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plus', '0012_emailverificationtoken'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhoneVerificationCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=20, verbose_name='手機號碼')),
                ('code', models.CharField(max_length=6, verbose_name='驗證碼')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('expires_at', models.DateTimeField(verbose_name='過期時間')),
                ('is_used', models.BooleanField(default=False, verbose_name='是否已使用')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP 地址')),
            ],
            options={
                'verbose_name': '手機驗證碼',
                'verbose_name_plural': '手機驗證碼管理',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['phone', 'code', 'is_used'], name='plus_phonev_phone_d7fa67_idx')],
            },
        ),
    ]
