# Generated by Django 5.2.8 on 2025-12-29 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plus', '0013_phoneverificationcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='needs_profile_update',
            field=models.BooleanField(default=False, verbose_name='需要更新資料'),
        ),
    ]
