# Generated by Django 5.2.8 on 2025-12-29 19:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plus', '0014_customuser_needs_profile_update'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailChangeRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('new_email', models.EmailField(max_length=254, verbose_name='新電子郵件')),
                ('token', models.CharField(max_length=64, unique=True, verbose_name='驗證 Token')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('expires_at', models.DateTimeField(verbose_name='過期時間')),
                ('is_used', models.BooleanField(default=False, verbose_name='是否已使用')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP 地址')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_change_requests', to=settings.AUTH_USER_MODEL, verbose_name='用戶')),
            ],
            options={
                'verbose_name': '電子郵件變更請求',
                'verbose_name_plural': '電子郵件變更請求管理',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['token', 'is_used'], name='plus_emailc_token_e4aa31_idx')],
            },
        ),
    ]
