# Generated by Django 5.2.8 on 2025-12-29 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plus', '0016_alter_customuser_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='email_verified',
            field=models.BooleanField(default=False, verbose_name='電子郵件已認證'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='phone_verified',
            field=models.BooleanField(default=False, verbose_name='手機號碼已認證'),
        ),
    ]
