# Generated by Django 5.2.8 on 2025-12-29 22:24

from django.db import migrations, models


def update_is_verified(apps, schema_editor):
    """更新現有用戶的 is_verified 狀態"""
    CustomUser = apps.get_model('plus', 'CustomUser')
    # 更新所有用戶：如果 phone_verified 或 email_verified 任一為 True，則 is_verified = True
    CustomUser.objects.filter(phone_verified=True).update(is_verified=True)
    CustomUser.objects.filter(email_verified=True).update(is_verified=True)
    # 如果兩者都為 False，則 is_verified = False（這應該已經是默認值）


def reverse_update_is_verified(apps, schema_editor):
    """反向遷移：不需要做任何事"""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('plus', '0019_alter_customuser_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='is_verified',
            field=models.BooleanField(default=False, editable=False, help_text='自動計算：手機或電子郵件任一驗證即為已驗證', verbose_name='是否已驗證'),
        ),
        migrations.RunPython(update_is_verified, reverse_update_is_verified),
    ]
