# Generated by Django 5.2.8 on 2026-08-30 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plus', '0020_alter_customuser_is_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='coupon_code',
            field=models.CharField(blank=True, max_length=50, verbose_name='優惠券代碼'),
        ),
        migrations.AddField(
            model_name='order',
            name='inventory_held',
            field=models.BooleanField(default=False, verbose_name='是否仍預扣庫存'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', 'is_read'], name='plus_notifi_user_id_fc726a_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['user', '-created_at'], name='plus_order_user_id_72f81c_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['status', 'is_featured'], name='plus_produc_status_dd35c1_idx'),
        ),
    ]
