# Generated by Django 5.2.8

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plus', '0021_order_coupon_inventory_and_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='carrier',
            field=models.CharField(blank=True, choices=[('', '尚未指定'), ('hct', '新竹物流'), ('tcat', '黑貓宅急便'), ('kerry', '嘉里大榮'), ('seven_eleven', '7-ELEVEN 交貨便'), ('family_mart', '全家店到店'), ('other', '其他')], max_length=30, verbose_name='物流商'),
        ),
        migrations.AddField(
            model_name='order',
            name='invoice_carrier',
            field=models.CharField(blank=True, max_length=64, verbose_name='載具／捐贈碼'),
        ),
        migrations.AddField(
            model_name='order',
            name='invoice_tax_id',
            field=models.CharField(blank=True, max_length=20, verbose_name='統一編號'),
        ),
        migrations.AddField(
            model_name='order',
            name='invoice_title',
            field=models.CharField(blank=True, max_length=100, verbose_name='發票抬頭'),
        ),
        migrations.AddField(
            model_name='order',
            name='invoice_type',
            field=models.CharField(choices=[('personal', '個人／載具'), ('company', '公司戶統編'), ('donate', '捐贈發票')], default='personal', max_length=20, verbose_name='發票類型'),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_method',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='plus.shippingmethod', verbose_name='配送方式'),
        ),
        migrations.AddField(
            model_name='order',
            name='tracking_number',
            field=models.CharField(blank=True, max_length=80, verbose_name='物流單號'),
        ),
        migrations.AddField(
            model_name='order',
            name='tracking_url',
            field=models.URLField(blank=True, verbose_name='物流查詢網址'),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('cod', '貨到付款'), ('test_payment', '測試付款'), ('linepay', 'LINE Pay'), ('ecpay', '綠界科技 ECPay')], default='cod', max_length=50, verbose_name='支付方式'),
        ),
        migrations.CreateModel(
            name='ReturnRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('defective', '商品瑕疵'), ('wrong_item', '寄錯商品'), ('not_as_described', '與描述不符'), ('changed_mind', '不想買了'), ('other', '其他')], max_length=30, verbose_name='原因')),
                ('detail', models.TextField(verbose_name='說明')),
                ('status', models.CharField(choices=[('pending', '待審核'), ('approved', '已核准'), ('rejected', '已拒絕'), ('received', '已收回商品'), ('refunded', '已退款'), ('cancelled', '已取消')], default='pending', max_length=20, verbose_name='狀態')),
                ('admin_notes', models.TextField(blank=True, verbose_name='後台備註')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='申請時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='return_requests', to='plus.order', verbose_name='訂單')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='申請人')),
            ],
            options={
                'verbose_name': '退貨申請',
                'verbose_name_plural': '退貨申請',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NewsletterSubscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='電子郵件')),
                ('is_active', models.BooleanField(default=True, verbose_name='訂閱中')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
            ],
            options={
                'verbose_name': '電子報訂閱',
                'verbose_name_plural': '電子報訂閱',
                'ordering': ['-created_at'],
            },
        ),
    ]
