# Generated by Django 5.2.8 on 2026-09-03 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plus', '0022_order_shipping_invoice_returns_newsletter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newslettersubscriber',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='訂閱時間'),
        ),
    ]
