# Generated by Django 5.2.8

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plus', '0023_alter_newslettersubscriber_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='custom_foods', to=settings.AUTH_USER_MODEL, verbose_name='自訂者'),
        ),
        migrations.CreateModel(
            name='ShippingAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(default='住家', max_length=40, verbose_name='名稱')),
                ('name', models.CharField(max_length=100, verbose_name='收件人')),
                ('phone', models.CharField(max_length=20, verbose_name='電話')),
                ('address', models.TextField(verbose_name='地址')),
                ('is_default', models.BooleanField(default=False, verbose_name='預設')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipping_addresses', to=settings.AUTH_USER_MODEL, verbose_name='會員')),
            ],
            options={
                'verbose_name': '收件地址',
                'verbose_name_plural': '收件地址',
                'ordering': ['-is_default', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkoutLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity', models.CharField(choices=[('walk', '走路／散步'), ('run', '跑步'), ('cycle', '騎車'), ('swim', '游泳'), ('weight', '重量訓練'), ('yoga', '瑜珈／伸展'), ('hiit', 'HIIT'), ('other', '其他')], max_length=20, verbose_name='活動')),
                ('duration_minutes', models.PositiveIntegerField(verbose_name='時間（分鐘）')),
                ('calories_burned', models.PositiveIntegerField(default=0, verbose_name='消耗熱量')),
                ('notes', models.CharField(blank=True, max_length=200, verbose_name='備註')),
                ('logged_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='記錄時間')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workout_logs', to=settings.AUTH_USER_MODEL, verbose_name='用戶')),
            ],
            options={
                'verbose_name': '運動記錄',
                'verbose_name_plural': '運動記錄',
                'ordering': ['-logged_at'],
            },
        ),
        migrations.CreateModel(
            name='WaterLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_ml', models.PositiveIntegerField(default=250, verbose_name='水量（ml）')),
                ('logged_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='記錄時間')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='water_logs', to=settings.AUTH_USER_MODEL, verbose_name='用戶')),
            ],
            options={
                'verbose_name': '飲水記錄',
                'verbose_name_plural': '飲水記錄',
                'ordering': ['-logged_at'],
            },
        ),
    ]
