# Generated by Django 5.2.17 on 2026-09-05 20:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plus', '0025_health_goals_and_daily_checkin'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', '待處理'), ('confirmed', '已確認'), ('processing', '處理中'), ('shipped', '已出貨'), ('delivered', '已送達'), ('completed', '已完成'), ('cancelled', '已取消'), ('refunded', '已退款')], max_length=20, verbose_name='訂單狀態')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='更新時間')),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='plus.order')),
            ],
            options={
                'verbose_name': '訂單處理紀錄',
                'verbose_name_plural': '訂單處理紀錄',
                'ordering': ['-created_at', '-pk'],
            },
        ),
    ]
