# Generated by Django 5.2.17 on 2026-09-05 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plus', '0026_orderevent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productimage',
            options={'ordering': ['-is_primary', 'sort_order', 'pk'], 'verbose_name': '商品圖片', 'verbose_name_plural': '商品圖片管理'},
        ),
    ]
