# Generated by Django 5.2.17 on 2026-09-05 23:44

import django.db.models.deletion
from django.db import migrations, models


def reserve_existing_coupons(apps, schema_editor):
    apps.get_model('plus', 'Order').objects.using(schema_editor.connection.alias).filter(
        inventory_held=True,
    ).exclude(coupon_code='').exclude(status__in=['cancelled', 'refunded']).update(coupon_reserved=True)


class Migration(migrations.Migration):

    dependencies = [
        ('plus', '0027_alter_productimage_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestLimit',
            fields=[
                ('key', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('count', models.PositiveIntegerField(default=0)),
                ('expires_at', models.DateTimeField(db_index=True)),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='coupon_reserved',
            field=models.BooleanField(default=False, verbose_name='優惠券使用次數尚未返還'),
        ),
        migrations.CreateModel(
            name='PaymentReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(max_length=20)),
                ('transaction_id', models.CharField(max_length=200)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('needs_review', models.BooleanField(default=False, verbose_name='待人工對帳')),
                ('reason', models.CharField(blank=True, max_length=200)),
                ('resolution', models.TextField(blank=True, verbose_name='對帳／退款處理紀錄')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_receipts', to='plus.order')),
            ],
            options={
                'verbose_name': '付款對帳紀錄',
                'verbose_name_plural': '付款對帳紀錄',
                'constraints': [models.UniqueConstraint(fields=('provider', 'transaction_id'), name='unique_provider_receipt')],
            },
        ),
        migrations.RunPython(reserve_existing_coupons, migrations.RunPython.noop),
    ]
