# Generated by Django 5.2.17 on 2026-09-05 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plus', '0028_payment_integrity'),
    ]

    operations = [
        migrations.AddField(
            model_name='returnrequest',
            name='refund_reference',
            field=models.CharField(blank=True, max_length=200, verbose_name='實際退款憑證／交易編號'),
        ),
        migrations.AddField(
            model_name='returnrequest',
            name='restock_items',
            field=models.BooleanField(default=False, verbose_name='已驗收可重新販售，退回庫存'),
        ),
    ]
